version: "3.3"
services:
  pq_db:
    image: postgres
    volumes:
      - ./tmp/pq_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=javy
      - POSTGRES_PASSWORD=123123
      - TZ=PRC
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - "5432:5432"

  mysql:
    image: mysql:5.7.28
    volumes:
      - ./tmp/mysql_data:/var/lib/mysql
    command: [
        #使用 command 可以覆盖容器启动后默认执行的命令
        '--character-set-server=utf8mb4', #设置数据库表的数据集
        '--collation-server=utf8mb4_unicode_ci', #设置数据库表的数据集
    ]
    environment:
      - MYSQL_ROOT_PASSWORD=123123
      - ALLOW_IP_RANGE=0.0.0.0/0
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"

  redis:
    image: redis:5.0.7
    command: redis-server --requirepass 123123 --appendonly yes
    volumes:
      - db_redis:/data
        #- ./conf/redis.conf:/etc/conf/redis.conf
    ports:
      - "6379:6379"
    environment:
      #this is not usage
      - PASSWORD=123123

volumes:
  db_redis:


