#!/usr/bin/env sh
# Author: javy liu
#Date & Time: 2021-01-25 15:45:15
#Description:
docker run -it --name pq_db --restart always -e TZ=PRC -e POSTGRES_USER='javy' -e POSTGRES_PASSWORD='123123' -e ALLOW_IP_RANGE=0.0.0.0/0 -v `pwd`/tmp/pq_data:/var/lib/postgresql/data -p 5432:5432 -d postgres

