# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: 192.168.30.33
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: javy
  password: <%= Rails.application.credentials.dev_db_pwd %>

development:
  primary:
    <<: *default
    database: api_base_development

  metedata:
    pool: 5
    url: <%= Rails.application.credentials.data_platform_metedata_url_dev %>

  pipstat:
    pool: 5
    url: <%= Rails.application.credentials.data_platform_pipstat_url_dev %>

  account:
    pool: 5
    url: <%= Rails.application.credentials.data_account_url_dev%>
test:
  primary:
    <<: *default
    database: api_base_test
  metedata:
    pool: 5
    url: <%= Rails.application.credentials.data_platform_metedata_url_test %>

  pipstat:
    pool: 5
    url: <%= Rails.application.credentials.data_platform_pipstat_url_test %>

  account:
    pool: 5
    url: <%= Rails.application.credentials.data_account_url_test %>

production:
  primary:
    <<: *default
    database: api_base_production
    password: <%= Rails.application.credentials.pro_db_pwd %>

  workflow:
    adapter: mysql2
    encoding: utf8
    username: attendance
    database: attendance
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    password: <%= Rails.application.credentials.workflow_db_pwd %>
    port: 3306
    host: 192.168.0.189

  metedata:
    pool: 5
    url: <%= Rails.application.credentials.data_platform_metedata_url %>

  pipstat:
    pool: 5
    url: <%= Rails.application.credentials.data_platform_pipstat_url %>

  redmine:
    pool: 5
    url: <%= Rails.application.credentials.redmine_db_url  %>

  account:
    pool: 5
    url: <%= Rails.application.credentials.data_account_url %>
